"""
Insight data structure for Claude-generated insights.

The Insight class is a simple container for insights generated by Claude.
All insight generation logic is now handled by Claude, not rule-based code.
"""

from typing import List, Optional
from dataclasses import dataclass, field


@dataclass
class ChartDataPoint:
    label: str
    value: float
    color: Optional[str] = None   # hex "#RRGGBB"


@dataclass
class ChartSpec:
    type: str   # "bar"|"bar_stacked"|"column"|"column_stacked"|"line"|"area"|
                # "pie"|"donut"|"scatter"|"bubble"|"radar"|
                # "kpi"|"heatmap"|"table"|"funnel"|"treemap"|"gauge"
    # bar / column / pie / donut / funnel / treemap
    data: Optional[List[ChartDataPoint]] = None
    # line / area / scatter / bubble / radar
    series: Optional[List[dict]] = None
    title: str = ""
    highlight: str = ""       # bar/column: label to accent-colour
    # kpi
    value: str = ""
    label: str = ""
    subtitle: str = ""
    # scatter/bubble axis labels
    x_label: str = ""
    y_label: str = ""
    # heatmap
    rows: Optional[List[str]] = None
    columns: Optional[List[str]] = None
    values: Optional[List[List[float]]] = None
    value_format: str = ".1f"
    # table
    table_columns: Optional[List[str]] = None
    table_rows: Optional[List[List[str]]] = None
    highlight_col: int = 0
    # gauge
    max_value: float = 100.0
    threshold: Optional[float] = None   # reference line on arc


@dataclass
class BulletPoint:
    text: str
    chart: Optional[ChartSpec] = None


@dataclass
class Insight:
    """A compelling, actionable insight generated by Claude"""
    headline: str  # Short, punchy headline with specific number
    bullet_points: List[BulletPoint]  # 2-3 supporting insights
    source_numbers: List[str]  # Numbers used (for validation)


def parse_chart_spec(raw: dict) -> Optional[ChartSpec]:
    """Maps JSON dict to ChartSpec dataclass."""
    if not raw or not isinstance(raw, dict):
        return None

    chart_type = raw.get('type', '').lower().strip()
    if not chart_type:
        return None

    # Parse data points list (for bar/column/pie/donut/funnel/treemap)
    data = None
    if 'data' in raw and raw['data'] is not None:
        data = []
        for item in raw['data']:
            if isinstance(item, dict):
                label = str(item.get('label', ''))
                try:
                    value = float(item.get('value', 0))
                except (TypeError, ValueError):
                    value = 0.0
                color = item.get('color') or item.get('colour')
                data.append(ChartDataPoint(label=label, value=value, color=color))

    # Parse series (for line/area/scatter/bubble/radar)
    series = raw.get('series')

    # Parse heatmap values
    heatmap_values = raw.get('values')

    # Parse table rows (key 'rows' in table spec means table data rows)
    table_rows = None
    table_columns = None
    if chart_type == 'table':
        table_columns = raw.get('columns')
        table_rows = raw.get('rows')

    return ChartSpec(
        type=chart_type,
        data=data,
        series=series,
        title=raw.get('title', ''),
        highlight=raw.get('highlight', ''),
        value=str(raw.get('value', '')),
        label=raw.get('label', ''),
        subtitle=raw.get('subtitle', ''),
        x_label=raw.get('x_label', ''),
        y_label=raw.get('y_label', ''),
        rows=raw.get('rows') if chart_type == 'heatmap' else None,
        columns=raw.get('columns') if chart_type == 'heatmap' else None,
        values=heatmap_values if chart_type == 'heatmap' else None,
        value_format=raw.get('value_format', '.1f'),
        table_columns=table_columns,
        table_rows=table_rows,
        highlight_col=int(raw.get('highlight_col', 0)),
        max_value=float(raw.get('max', raw.get('max_value', 100.0))),
        threshold=float(raw['threshold']) if raw.get('threshold') is not None else None,
    )


def parse_bullet_point(raw) -> BulletPoint:
    """Accepts string (old format) or dict with 'text'/'chart' keys (new format)."""
    if isinstance(raw, str):
        return BulletPoint(text=raw, chart=None)

    if isinstance(raw, dict):
        text = raw.get('text', '')
        chart_raw = raw.get('chart')
        chart = parse_chart_spec(chart_raw) if chart_raw else None
        return BulletPoint(text=text, chart=chart)

    # Fallback for unexpected types
    return BulletPoint(text=str(raw), chart=None)


def parse_bullet_points(raw_list) -> List[BulletPoint]:
    """Public entry point: convert raw insights list to List[BulletPoint]."""
    if not raw_list:
        return []
    return [parse_bullet_point(item) for item in raw_list]
