"""
Insight data structure for Claude-generated insights.

The Insight class is a simple container for insights generated by Claude.
All insight generation logic is now handled by Claude, not rule-based code.
"""

from typing import List
from dataclasses import dataclass


@dataclass
class Insight:
    """A compelling, actionable insight generated by Claude"""
    headline: str  # Short, punchy headline with specific number
    bullet_points: List[str]  # 2-3 supporting insights
    source_numbers: List[str]  # Numbers used (for validation)
